### ISSUE TITLE
[PATCH] fix a spelling mistake

### ISSUE THREAD

**Issue by fschlich** [szabgab/Pod-Tree#5]
In Debian we are currently applying the following patch to Pod-Tree.
We thought you might be interested in it too.

```
Description: fix a spelling mistake
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2010-06-22
```

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libpod-tree-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  Florian Schlichting,
  Debian Perl Group

**Comment by szabgab** [comment]
thanks
