### ISSUE TITLE
Fails when Code::TidyAll is installed and Perl::Tidy is 20181119

### ISSUE THREAD

**Issue by andk** [szabgab/Pod-Tree#8]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/b4bf0aae-ebca-11e8-b555-af575500f816

**Comment by andk** [comment]
If you feel like it: taking one step towards self-documenting test environment, you could beef up your Makefile.PL by calculating the hash containing the prereqs before calling WriteMakefile. Something like (untested):

``` perl
my $prereq_pm = {
                'File::Find'     => 1,
                'HTML::Stream'   => 1.49,
                'IO::File'       => 1,
                'IO::String'     => 1,
                'Pod::Escapes'   => 1.02,
                'Text::Template' => 1,
        };
for my $interesting_module (qw(
    Perl::Tidy
    Code::TidyAll
                              )) {
    eval "require $interesting_module";
    if (!$@) {
        $prereq_pm->{$interesting_module} ||= 0;
    }
}
```

and further down:

``` perl
    PREREQ_PM => $prereq_pm,
```

This would still not do any violence to users who have neither Perl::Tidy nor Code::TidyAll installed but it would document the installed versions of said modules in the report. In the standard way.

**Comment by cxw42** [comment]
Can this issue be closed?  I see the latest matrix is all green.

**Comment by andk** [comment]
Looks good, I'll close it. Thanks, everybody!
